name: Android Release Action

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'App version'
        required: true
        default: '3.0.1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11.0.22+7
      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts 
          versionCode: ${{github.run_number}}
          versionName: '${{ github.event.inputs.app_version }}'
