name: Android Release Action

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'App version'
        required: true
        default: '3.0.1'
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Get app version
        id: get_version
        run: |
          chmod +x gradlew 
          echo "BUILD_NUMBER=$( ./gradlew -q app:getNextBuildVersionNumber )" >> $GITHUB_ENV

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ env.BUILD_NUMBER }}
          versionName: '${{ github.event.inputs.app_version }}'

      - name: Commit version bump
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add app/build.gradle.kts
          git commit -m "Version bump to ${{ github.event.inputs.app_version }} (Build ${{ env.BUILD_NUMBER }}"
          git tag "${{ github.event.inputs.app_version }}({{ env.BUILD_NUMBER }})"
          git push --tags
