name: Android Release Action

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'App version'
        required: true
        default: '3.0.1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11.0.22+7

      - name: Get app version
        id: get_version
        uses: eriknyk/android-get-app-version-action@v1.0.1

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ steps.get_version.outputs.nextVersionCode }}
          versionName: '${{ github.event.inputs.app_version }}'

      - name: Commit version bump
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git commit -am "Version bump to '${{ github.event.inputs.app_version }} (Build ${{ steps.get_version.outputs.nextVersionCode }}'
          git push

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: '${{ github.event.inputs.app_version }} (Build ${{ steps.get_version.outputs.nextVersionCode }}'
          release_name: Release '${{ github.event.inputs.app_version }} (Build ${{ steps.get_version.outputs.nextVersionCode }}'
          body: |
            New release '${{ github.event.inputs.app_version }} (Build ${{ steps.get_version.outputs.nextVersionCode }})'
          draft: false
          prerelease: false
