name: Android Release Action

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'App version'
        required: true
        default: '3.0.1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11.0.22+7
      - uses: ults-io/mobile-version-bump-action@v2
      - name: Bump version
        with:
          android-project-path: / # required if you want to trigger Android version bump
          app-version: '${{ github.event.inputs.app_version }}' # optional param for Android & iOS version
